version: "3.9"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    tty: true
    restart: always
    volumes:
      - redis_data
    networks:
      database-app:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    tty: true
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - db_data:/db
    networks:
      database-app:
  calculator:
    build: .
    ports:
      - "2000:2000"
    depends_on:
      - database
      - redis
    volumes:
      - app_data:/app
    networks:
      database-app:
    environment:
      GIN_MODE: release
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: database
      POSTGRES_PORT: ${POSTGRES_PORT}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: redis
      APP_PORT: ${APP_PORT}
    restart: on-failure
volumes:
  db_data:
  app_data:
  redis_data:
networks:
  database-app: